[build]
    publish = "public"

[[plugins]]
    package = "netlify-plugin-checklinks"
[[plugins]]
    package = "netlify-plugin-html-validate"
    [plugins.inputs]
        ext = "html"
        config = ".htmlvalidate.json"
[[plugins]]
    package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
    	baseUrl = "https://www.aquiles.me"
    	sitemapPath = "/sitemap.xml"